version: "3"

services:
  web:
    image: nginx
    restart: always
    volumes:
      - ./build/web/:/usr/share/nginx/html/
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8000:80